# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_win.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1104, 399)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/新前缀/title.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#textEdit_3,#textEdit_4,#textEdit_5,#textEdit_6,#textBrowser{\n"
"    background-color: rgb(217, 217, 217);\n"
"}\n"
"#tableWidget{\n"
"    background-color: rgb(217, 217, 217);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setContentsMargins(-1, 9, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_3.addWidget(self.textEdit_3)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_4.addWidget(self.textEdit_4)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_5.setReadOnly(True)
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalLayout_5.addWidget(self.textEdit_5)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_6.setReadOnly(True)
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalLayout_6.addWidget(self.textEdit_6)
        self.horizontalLayout_7.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_9.addWidget(self.textBrowser)
        self.horizontalLayout_7.addWidget(self.groupBox_7)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_8.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_in = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_in.setChecked(True)
        self.radioButton_in.setObjectName("radioButton_in")
        self.horizontalLayout_8.addWidget(self.radioButton_in)
        self.radioButton_start = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_start.setObjectName("radioButton_start")
        self.horizontalLayout_8.addWidget(self.radioButton_start)
        self.radioButton_end = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_end.setObjectName("radioButton_end")
        self.horizontalLayout_8.addWidget(self.radioButton_end)
        self.radioButton_be = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_be.setObjectName("radioButton_be")
        self.horizontalLayout_8.addWidget(self.radioButton_be)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_8.addWidget(self.checkBox)
        self.pushButton_condition = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_condition.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_condition.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_condition.setObjectName("pushButton_condition")
        self.horizontalLayout_8.addWidget(self.pushButton_condition)
        self.pushButton_chinese = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_chinese.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_chinese.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_chinese.setObjectName("pushButton_chinese")
        self.horizontalLayout_8.addWidget(self.pushButton_chinese)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "筛选"))
        self.groupBox.setTitle(_translate("Form", "关键词列表"))
        self.groupBox_2.setTitle(_translate("Form", "筛选条件"))
        self.groupBox_3.setTitle(_translate("Form", "符合结果"))
        self.groupBox_4.setTitle(_translate("Form", "不符合结果"))
        self.groupBox_5.setTitle(_translate("Form", "含汉字"))
        self.groupBox_6.setTitle(_translate("Form", "无汉字"))
        self.groupBox_7.setTitle(_translate("Form", "日志"))
        self.radioButton_in.setText(_translate("Form", "包含"))
        self.radioButton_start.setText(_translate("Form", "开头"))
        self.radioButton_end.setText(_translate("Form", "结尾"))
        self.radioButton_be.setText(_translate("Form", "等于"))
        self.checkBox.setText(_translate("Form", "输出日志"))
        self.pushButton_condition.setText(_translate("Form", "条件筛选"))
        self.pushButton_chinese.setText(_translate("Form", "汉字筛选"))
import img_rc
